query Crags($country: String!, $input: FindCragsInput) {
    countryBySlug(slug: $country) {
        id
        name
        slug
        code
        crags(input: $input) {
            id
            slug
            name
            type
            nrRoutes
            orientation
            orientation
            orientations
            wallAngles
            seasons
            approachTime
            rainproof
            lon
            lat
            minDifficulty
            maxDifficulty
            defaultGradingSystem {
                id
            }
            area {
                id
                name
                slug
            }
            country {
                id
                name
                slug
                code
            }
        }
        areas(hasCrags: true) {
            id
            name
            slug
        }
    }
}
